name: marti_case
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.2
  flutter_secure_storage: ^9.2.4
  permission_handler: ^12.0.0+1
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
